-- Default configurations
require('plugins')
require('mappings')
require('settings')
require('actions')
require('highlight')

-- Plugin configurations
require('config.colorscheme')
require('config.colorizer')
require('config.comments')
require('config.icons')
require('config.lsp')
require('config.bufferline')
require('config.statusline')
require('config.tree')
require('config.treesitter')
require('config.autopairs')
require('config.formatter')
require('config.hop')
require('config.terminal')
